version: '3'
services:
  flyway:
    image: flyway/flyway:6.0.4
    command: -url=jdbc:postgresql://database:5432/postgres -user=postgres -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    container_name: database
    ports:
      - 5432:5432